---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _exercises
  label: Exercises
  create: all
  match: "**/*"
- type: directory
  path: _workouts
  label: Workouts
  create: all
  match: "**/*"
  templates:
  - workout-template
- type: directory
  path: _recipes
  label: Recipes
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
